version: '3.3'
services:
  api:
    image: springboot
    container_name: springboot
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/springboot
    ports:
      - "9500:8081"
    networks:
      - default
networks:
  default:
    external:
      name: docker